image: gitpod/workspace-base

tasks:
- name: install hifiasm
  init: |
    cd /workspace
    #hifiasm
    wget https://github.com/chhylp123/hifiasm/archive/refs/tags/0.19.6.tar.gz
    tar xvzf 0.19.6.tar.gz
    cd hifiasm-0.19.6
    make -j4
    cd ..
    #ln -s hifiasm-0.19.6/hifiasm
    #yak
    wget https://github.com/lh3/yak/archive/refs/tags/v0.1.tar.gz
    tar xvzf v0.1.tar.gz
    cd yak-0.1
    make -j4
    cd ..
    #ln -s yak-0.1/yak
    mkdir bin
    cd bin
    ln -s ../hifiasm-0.19.6/hifiasm
    ln -s ../yak-0.1/yak
    #HiFi reads
    wget https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/4DE3A234-8903-44C7-8BEF-86C5AF73F5B1--HG002-ASSEMBLY/HG002.HiFi.chr11.10M.fastq.gz
    #UL reads
    wget https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/4DE3A234-8903-44C7-8BEF-86C5AF73F5B1--HG002-ASSEMBLY/HG002.UL.chr11.10M.fastq.gz
    #pat reads
    #wget https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/4DE3A234-8903-44C7-8BEF-86C5AF73F5B1--HG002-ASSEMBLY/HG002.pat.chr11.10M.fastq.gz
    #mat reads
    #wget https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/4DE3A234-8903-44C7-8BEF-86C5AF73F5B1--HG002-ASSEMBLY/HG002.mat.chr11.10M.fastq.gz
    #HiC reads
    wget https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/4DE3A234-8903-44C7-8BEF-86C5AF73F5B1--HG002-ASSEMBLY/HG002.HiC.chr11.10M.R1.fastq.gz
    wget https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/4DE3A234-8903-44C7-8BEF-86C5AF73F5B1--HG002-ASSEMBLY/HG002.HiC.chr11.10M.R2.fastq.gz
    #HiFi bin files
    wget https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/4DE3A234-8903-44C7-8BEF-86C5AF73F5B1--HG002-ASSEMBLY/bin.tar.gz
    tar xvzf bin.tar.gz
    mkdir HiFi
    cd HiFi
    ln -s ../bin/HG002.chr11.10M.ec.bin
    ln -s ../bin/HG002.chr11.10M.ovlp.source.bin
    ln -s ../bin/HG002.chr11.10M.ovlp.reverse.bin
    ln -s ../bin/HG002.pat.chr11.10M.yak
    ln -s ../bin/HG002.mat.chr11.10M.yak
    mv ../bin/HG002.chr11.10M.hic.lk.bin .
    cd ..
    mkdir HiFi_UL_trio
    cd HiFi_UL_trio
    ln -s ../bin/HG002.chr11.10M.ec.bin HG002.chr11.10M.UL.trio.ec.bin
    ln -s ../bin/HG002.chr11.10M.ovlp.source.bin HG002.chr11.10M.UL.trio.ovlp.source.bin
    ln -s ../bin/HG002.chr11.10M.ovlp.reverse.bin HG002.chr11.10M.UL.trio.ovlp.reverse.bin
    ln -s ../bin/HG002.pat.chr11.10M.yak
    ln -s ../bin/HG002.mat.chr11.10M.yak
    mv ../bin/*UL*trio* .
    cd ..
    mkdir HiFi_UL_hic
    cd HiFi_UL_hic
    ln -s ../bin/HG002.chr11.10M.ec.bin HG002.chr11.10M.UL.hic.ec.bin
    ln -s ../bin/HG002.chr11.10M.ovlp.source.bin HG002.chr11.10M.UL.hic.ovlp.source.bin
    ln -s ../bin/HG002.chr11.10M.ovlp.reverse.bin HG002.chr11.10M.UL.hic.ovlp.reverse.bin
    mv ../bin/*UL*hic* .
  command: |
    cd /workspace/bin



    

workspaceLocation: "/workspace"
